package gov.samhsa.c2s.c2suiapi.infrastructure.dto;

import lombok.Data;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;

@Data
public class RequiredIdentifierSystem {
    @NotBlank
    private String system;
    /**
     * If the {@link RequiredIdentifierSystem#algorithm} is set to something other than {@link Algorithm#NONE},
     * then this identifier is generated by the system and <b>cannot</b> be set manually.
     */
    @NotNull
    private Algorithm algorithm;

    public enum Algorithm {
        NONE,
        UUID,
        MRN
    }
}
